### PR TITLE
create controllers, models, factories, dummmy data round one

### PR DESCRIPTION
**Pull request by KeeshaCain**
The comment above states what we did during class, if anyone needs further explanation please ask :)

### CODE REVIEW

**Comment by freethewhat** [comment]
Looks like there are some issues with testing. @iverunamok can you take a peak at this with @KeeshaCain?

**Comment by iverunamok** [comment]
sure. we can take a look at this tonight if @KeeshaCain is available to meet up? I get off around 6 tonight from Victor.

**Comment by KeeshaCain** [comment]
I can't meet up tonight! Eek! What do I need to look at? I will have time at work tonight!

**Comment by iverunamok** [comment]
No worries Keesha, I think it's more on the travisit checking stuff... a
test wa's probably firing and our database might not be totally hooked up
yet. I will check it out and update you! :*

**Comment by KeeshaCain** [comment]
Wonderful! Thanks Kelsey! I'm going to dive into the documentation for travis ci tonight.

**Comment by iverunamok** [comment]
@KeeshaCain hope your night at work went well! I think I have found a possible hang-up... I think we need to change our database.php file to match all the things we are using instead of homestead... https://laracasts.com/discuss/channels/testing/how-to-specify-a-testing-database-in-laravel-5... feel free to play... I would like to play with you on this tomorrow if possible? Or I can just pull your branch down and try a few things too. let me know how far you get in your studies tonight and if you took a deeper look!

**Pull request merged**
