### PR TITLE
first draft timeline

### PR DESCRIPTION
**Pull request by nstn8**
This is the first draft of the timeline.  Still not sure how much time testing is gonna require. 
 I would bet we will be doing testing almost everyday along with everything else.  @freethewhat what do you think?  @ed42311 same question.

### CODE REVIEW

**Comment by freethewhat** [comment]
@iverunamok Do you know anything about Travis CI and these failed checks?

**Comment by ed42311** [comment]
@iverunamok you need to pull in your travisCI branch or the build will continue to fail, there is no travis.yml atm and it runs default, we ere building against your branch

**Comment by ed42311** [comment]
@nstn8 that timeline seems fair, if a bit ambitious.  Testing can take as long as you like, what you might want to do is say something like, we'll build e2e tests for all forms or something like that confines your scope.

**Comment by iverunamok** [comment]
@freethewhat I do not still. I have had work all weekend, all I know is what Ed and I breezed over after code school. Sounds like he needed me to push up though regardless, so I will do some more research tonight after work to find that answer for you. I commented where I found everything, but it will probably just take more digging of the errors we are seeing to fully understand.

**Pull request merged**
